
production:
  adapter: mysql
  encoding: utf8
  database: qameha_web
  username: root
  password: sQameha88260

development:
  adapter: mysql
  encoding: utf8
  database: qameha_sandbox
  username: root
  password: galactus
  host: localhost
  socket: /opt/local/var/run/mysql5/mysqld.sock
#  socket: /tmp/mysql.sock
