---
  'qameha':
    :user_name: do_not_reply@qameha.com
    :password: qameha88260
    :domain: qameha.com
  'qameha2':
    :user_name: qameha@gmail.com
    :password: qameha88260
    :domain: gmail.com
